spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test # 메모리 내 데이터베이스 URL
    driver-class-name: org.h2.Driver # H2 드라이버 클래스
    username: sa # 기본 사용자 이름
    password: # 기본 비밀번호는 비워둡니다.
  h2:
    console:
      enabled: true # H2 콘솔을 활성화합니다.
      path: /h2-console # H2 콘솔의 접근 경로
  jpa:
    hibernate:
      ddl-auto: update # 일단 우리는 스키마 생성해야하니까~
    properties:
      hibernate:
        format_sql: true # 얘는 실제 디비로 나가는 sql을 보여줍니다
  sql:
    init:
      mode: always # 애플리케이션 시작 시 스크립트 초기화 (기본값: embedded)
  config:
    import: optional:application-secret.yml


jwt:
  secret: E6n3znBWQHGs8mo6IWp/ys20gIeVj5TfLYl0Gl393i3R2+cKzpCvRddOZwYJcQtSwEzv3+pK0k+uFkSCE4oJXb2IyURCb+gNd7lj+S2EJtCexw0izO7y5SIFYiX4IjAsUiINjrw1zl4xTPo4iJUMdHdk5DtDQikW0bC5DdLW4/KqpqP9VHLlSX/HbD52+iBZDLcbzWjJo4UhnSyrit8z9Li2HLb94wtO58WGKTpeANOy9G4qxSVNk+qGTozu8+ISsMFZrza1kOsNBcBsU9Op3ZbmVqIP8rTpSet7s/AAPSqPppjpuDPtgarOrcGbz6Qy45ixwFjOs2/g0eWB5189DA==